apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gomoku
resources:
  - namespace.yaml
  - gomoku-env.sealedsecret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/seol-jy/gomoku-server
    newTag: "3e85f7c"  # gomoku 레포 server-image 워크플로가 커밋 SHA 로 갱신
