---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: portfolio-chat
spec:
  encryptedData:
    .dockerconfigjson: AgCa8yg819Vxwp/QhC8RsqZFfiVvpypVsGhA3S0jbYpoA7d2nqN/FknhAZgoWt576ayqjto1VWGETu/qh78BJD89oDq1lbdTtSPbnw7bYb7tJug5N7fhm+mUwAr6KUu/yVgBr0EuPAhTDOSvnMzBs/C8R2EskyQeWV0G/SanWWNiixvzWe+e3uvCPlFvI0HokYBe7w8JbBVkp1/8ivbx/1Q1CzIPO9kkDPMYKPbqRpvi6RCbsd2E32PFnBPjglO9WEzwL/4hvHs4m744OtrXayhT5IcREvKAaw1i0CvO14EFK9BxmpNx/ggg6Td2EsU3ZfZn/zxtiUhz9bdOZhPEti6hLe2fKXmF80J4AUVM397f/n7MOO/GYXQL6PtBEDUlMzmq69hf10Egc+NPpi6+qeWKbeSmXQv5wRzBfhXpFopuAssLqa2ThQoa4qt71t3TMAS2APRMtRhYBgQJ1sLVxH9nI/F7Td+EVv11Hm0SsNpGNYRXdhZWWooEU4VSIEhW7aCdIjU+LHRMk9XDjsteM0bv8/6ovWIW702RfGZ63W6nL1NnZwOk8rAuL6TnPTaYJB7+kozQR+0pBNdvHjAlrytNa3DBR2wFH5EUeGqn6OfjDabQtC9oyc1Cvn69/7qPRs0evv27H/mkSyr8Z7kNlRzIukpTYb+CrjDS6TrngmeJ6eJCaBZ49pkdVKmNpMRETRKHu0lnHVq87QFMKDmUs2fMDTeZ5KQHJbSkUR3eVtH6chOLV6yig/YNpb4C/iw7zhLj5Az8DIsjhp4DrzX2tYF20aIlJQWXR5maaHOzbQvj4Hw++EX6OVemzfeF8F8ymjIJLZgJW5eCw0tWvzvi+XwiqXotEv0dCrQeIhXP7L7G6JbVKxufN/uPKnR+5uYqkceAhfc0YsnmEh749WxdR5MTDKKXpG9aoCTTs8fd
  template:
    metadata:
      name: ghcr-pull
      namespace: portfolio-chat
    type: kubernetes.io/dockerconfigjson
