apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio-chat
resources:
  - namespace.yaml
  - portfolio-chat-env.sealedsecret.yaml
  - ghcr-pull.sealedsecret.yaml
  - postgres-init.configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - vmpodscrape.yaml
images:
  - name: ghcr.io/seol-jy/portfolio-chat-backend
    newTag: 826a703
