apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
