apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: portfolio-chat
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: portfolio-chat
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
