---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBjAxCJYzNJdd2KgS9ZijIHJEcFNYsQFEA6nOAlMLmwheOfyUpKjaFgIfm0qGT7qYy5RsqnFWBnd0btbuhv6etTl2KA3y1WVv9YrmJC2+0Ygf1sm8i00g8sZ3+lDV2DyxkqDK0MXQcLZZxtmZF0hmotk8ZDAcfveRELUVW1sWRwH8zgqISGfcleJd383HMTnXlQiGQkQ/qFqQKpkoNyTx8M2wS8iFH1w+PKdUFUTaMey2UBrhi1nTAGNyuAd9TnjKv7yom/8ljTFOETg/tfY37VTVPH3jEUw0ao/AnAXs3O1JtqRR118xH6NaUeQzFZxUaQXOgEbE4X1axjWdJqVvMwFJbg3Sy5eA0LUawpGUCE1Y+nXn9EWeS+hWEkOVb6KvcEZle1Vockk/K0Nxc++HI0IPGCx3fUcpqm+1vz3Dv+yrZakkR3UzO6FK3tjcJMChXUaitijm5qrlMmyZb19NhQBKZ1ZBVvm8xMj0gEp1WzRSjnSz1ftlbnylOuCLSnFW6r6cCc0j9giB7rHzLQfWW7PYyN7B+m6sA45plzEEhTfe8DAWWv4DeDoiocSuB6rpFAd4emn6dFvJHoNN2aaS714rI4sCvU+yD7U3gM+S5VweysztucT/uwFgDPYGkm402PzD4/+BtERkDl6Vw5WeeZVqrw5BzLiqt/7gKPvikpOag+Jt4U4U4V6o42+1izMfSbHkBWXB2k1v9Ptec3R/XvoQksvARslc3lo9T8ZtzKW6HiGOzubP3fzXjOA8+84jBjsUBubw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
