---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCbT3hoimkv4ywjuH1a4cevv2nufN2Ie1lXCt0RN1LMFypVBj8lcPwGy2s9YfjpHn6VomCxqGYtoR6i7yLvNzrUf61rD1sFJM9zbDNAsE4T+hlrxneOPiqp91K50nqJTOmhV9tKF8xQIVv05LS66upceRxbOo0Bv54oNetXuu1ZwdFfhI+AOiEMVThsFvtutuv7Z0gH93uGcGKwTX8wNd+wUXBNbcXCm2eCkCKJy0VA80kIb69BtVxwavXfZ4o43//PmjY56muP5HfeypeK7wNQ8bNn8vnQ1Gpgolxw2oX6PD+GSQ8J5rbRmnSZoB0ItfWTdG4/eqTYRqWKE4YWBIYcZ1rni97qMVeqizRren8cpDAhK4fKBpA95tpU1Ejm/Bmq8V2pha2l56TIrV0p/BoQ1rW0Jf33y9zWnO4fXRXYlF1qp4PHmLddF7B36KuG1CMZcMeRjjM9XQxvZoDkklbw50BRxv12dJtANyECL0iRF+DMOctTIblChqFmrcf6C9oGSrYZT/BhHUnpNR6U0nvHhm+JN8D+jLRrS/yWNn3eDuGeRrM0ibJw/f2/A34ldzPUk3hA0VvaY0A807CVQ0UBTZ5MR7mZQqCNFm/8TQ5v2h0cthJc4ia0RM94wrzQpltXKEyOKawW9aR+cUJKVJow/Xf1MWf+A+CvAhcT698HJD7k6uWbJWYTcx3Cl+EzMkD620wFr3KNqbziASYVfcon73YNWjPxcL7zqvcyJsTUTA==
    admin-user: AgBATEbPrHspHIWG2H7WyLw4yQhYHwEAQUmPjN1QYqgHQx1iv7B3dA37+9A9N3gqVdFenUBK/gBmfZEH1p86BIBS9KPMkRoY+vKwQEOduArQpYjCSAZyALi5Z466ZAHjkjZPVHXcC/4fPWTSlpkCM9eh5gPaSVMJ+iZIF5lVJOabdy/BzADoOXZpZeznFwVWNIfikdN1GXFlshy01xbfmdMxRuSvH87sdq7fYh92GDNz0EIfNe/Z60rMdDpGuBlPx9RQxdxrLqxnQwulhZrCaxE2lGFvrw8/I50uepHyquxD+qv75ghbwFVEVxONKBwzPPs2hleuMAPBO0pBlg+e5pX5DcM3rDIXwFIP52rUQfICI23y7i7+wgenqYGicto3DuIyOAzIIbvF+KfX2/jsYRA2PQvO4JywqHypViQsW4YvhyxbwlatlWBcO9SwjyHLk/CJ/uUZ1bvoMyQ3gY7zhbUVMKAqyX/vYfMwFYMi7PntAdG+PJ9nPL1XkVJ2mBKfTc9UnNR8EsfQJUjaxbfjifq5oTPgACcus+gMru9b+ceiXY+dm507kCb21ClqpfPwht398skipCTL8WhD2tdOJgnnD+5EgCSNY3Uiv3Y47YJEA+D1sdNyX6VS1IFElnF8A0h4pRMskxaxrYYgz+V7p40OUMjA0R4ckvGdEIoCAY9reNAnvstSoUq9w4ClTzM5UgG/Ijr48Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
