apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: marketpulse-producer
resources:
  - namespace.yaml
  - toss-openapi.sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - vmpodscrape.yaml
configMapGenerator:
  - name: producer-config
    envs: [symbols.env]

images:
  - name: ghcr.io/seol-jy/marketpulse-producer
    newTag: 2b36ebe3a5a82c0908bba7e428a25fa68aff0ccf
